collections_dir: ./src/ourail

port: 10025

title: Ourai L.

collections:
  pages:
    output: true
    permalink: /:path/

# YAML frontmatter
defaults:
  # 默认
  - scope:
      path: ""
    values:
      layout: default
  # 页面
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  # 文章
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      css:
        - pages/post
      js:
        - initializers/time
        - initializers/lazyload
      author:
        name: Ourai L.
        email: ourairyu@gmail.com
        uri: https://ourai.github.io/
        slug: ourai
        twitter: ntksol
      siblings: true
      comments: true



# =====
# Plugin-specific configurations
# =====

# Jekyll Feed
feed:
  path: atom.xml
name: Ourai L.
author:
  name: Ourai L.
  email: ourairyu@gmail.com
  uri: https://ourai.github.io/
  twitter: ntksol
github:
  url: https://ourai.github.io



# =====
# Customized configurations
# =====

ourairyu:
  site:
    name: Ourai L.
    url: https://ourai.github.io
    domain: ourai.github.io
    master: ourai
    statistic: false

# Modules
module:
  comment: false
  share: false

# 站点首页配置
site-homepage:
  modules:
    moment:
      enabled: false
    person:
      enabled: false
    topic:
      enabled: false
    post:
      enabled: false

site-modules:
  taxonomy: true
  blog: false
  murmur: false
  weekly: false
  otaku: false
  life: false
  mine:
    pagination:
      limit: 30
  social:
    moment:
      limit: 30
